const fs = require('fs');

const base = {
    movies: 'Movies',
    series: 'TV Shows',
    searchPlaceholder: 'Search movies and TV shows...',
    allGenres: 'All genres',
    loadMore: 'Load more',
    downloadsTab: 'Download',
    home: 'Home',
    profile: 'Profile',
    watch: 'Watch',
    recommendations: 'Recommendations',
    loading: 'Loading...',
    notFound: 'Nothing found',
    movieNotFound: 'Movie not found',
    descriptionMissing: 'No description available.',
    myFavorites: 'My Favorites',
    emptyFavorites: 'It is empty here so far 🎬',
    vipStatus: 'VIP Status',
    buyLifetime: 'Buy Lifetime',
    buyLifetimeSub: 'One-time payment for endless streaming',
    vipActive: 'VIP active until',
    lifetimeActive: 'Lifetime VIP active',
    privateModeTitle: 'Private 🍓 Section',
    privateModeDesc: 'Exclusive adult content. Available only for VIP subscribers.',
    privateBotTitle: 'Private 18+ Bot',
    open18Bot: 'Open 18+ Bot',
    buyVipForAccess: 'Buy VIP for access',
    privateCollection: 'Private Collection',
    privateCollectionDesc: 'Private collection of premium content. Available only for VIP members.',
    unlockWithStars: 'Unlock with Telegram Stars',
    language: 'Language',
    theme: 'Theme',
    themeAuto: 'Auto',
    themeLight: 'Light',
    themeDark: 'Dark',
    listenNow: 'Listen Now',
    trendingNow: 'Trending Now',
    thematicPlaylists: 'Playlists',
    topArtists: 'Top Artists',
    ambientSounds: 'Ambient Sounds',
    ambientSoundsDesc: 'Endless ambient — for sleep, meditation, focus',
    searchPlaceholderMusic: 'Artists, tracks...',
    searchPlaceholderRadio: 'Search...',
    back: 'Back',
    allTracksLoaded: 'All tracks loaded',
    vipRequired: 'VIP Required',
    vipRequiredDesc: 'This content is for VIP only',
    openBot: 'Open Bot',
    movies_and_series: 'Movies',
    radio_and_tv: 'Radio & TV',
    music: 'Music',
    privateContent: 'Private',
    favorites: 'Favorites',
    subtitle_movies: 'Movies & series, ad-free',
    subtitle_radio: 'Live streams and stations',
    subtitle_music: 'Millions of tracks, ad-free',
    subtitle_adult: 'Exclusive 18+ collection',
    tgLoginRequired: 'You need to log in via Telegram to access the Private section',
    tab_movies: 'Movies',
    tab_series: 'Series',
    tab_radio: 'Radio',
    tab_tv: 'TV',
    tab_music: 'Music',
    tab_private: 'Private',
    emptyList: 'List is empty',
    comingSoon: 'Coming soon...',
    player1: 'Player 1',
    player2: 'Player 2',
    buyVip: 'Buy VIP ⭐️',
    supportCreator: 'Support Creator',
    supportSubtitle: 'Crypto Transfer (USDT / TON)',
    supportContact: 'Contact Support',
    supportContactSubtitle: 'Contact the developer',
    tvWarning: 'Note: some channels might not work due to geo-blocks or offline provider servers. If a channel doesn\'t load, just try another one.',
    source1: 'Source 1',
    source2: 'Source 2',
    source3: 'Source 3'
};

const translations = {
  'ko-KR': { ...base, movies: '영화', series: '시리즈', home: '홈', profile: '프로필', searchPlaceholder: '검색...', watch: '시청하기', language: '언어' },
  'id-ID': { ...base, movies: 'Film', series: 'Serial', home: 'Beranda', profile: 'Profil', searchPlaceholder: 'Cari...', watch: 'Tonton', language: 'Bahasa' },
  'hi-IN': { ...base, movies: 'फिल्में', series: 'सीरीज़', home: 'होम', profile: 'प्रोफ़ाइल', searchPlaceholder: 'खोजें...', watch: 'देखें', language: 'भाषा' },
  'fa-IR': { ...base, movies: 'فیلم‌ها', series: 'سریال‌ها', home: 'خانه', profile: 'پروفایل', searchPlaceholder: 'جستجو...', watch: 'تماشا', language: 'زبان' },
};

console.log(JSON.stringify(translations, null, 2));
